export const Action = {
  GET_LATEST_COVID_DATA_REQ: "ACTION/GET_LATEST_COVID_DATA_REQ",
  GET_LATEST_COVID_DATA_OK: "ACTION/GET_LATEST_COVID_DATA_OK",
  GET_LATEST_COVID_DATA_ERR: "ACTION/GET_LATEST_COVID_DATA_ERR",

  GET_LATEST_COVID_PROVINCE_DATA_REQ: "ACTION/GET_LATEST_COVID_PROVINCE_DATA_REQ",
  GET_LATEST_COVID_PROVINCE_DATA_OK: "ACTION/GET_LATEST_COVID_PROVINCE_DATA_OK",
  GET_LATEST_COVID_PROVINCE_DATA_ERR: "ACTION/GET_LATEST_COVID_PROVINCE_DATA_ERR",

  GET_LATEST_COVID_TIME_SERIES_DATA_REQ: "ACTION/GET_LATEST_COVID_TIME_SERIES_DATA_REQ",
  GET_LATEST_COVID_TIME_SERIES_DATA_OK: "ACTION/GET_LATEST_COVID_TIME_SERIES_DATA_OK",
  GET_LATEST_COVID_TIME_SERIES_DATA_ERR: "ACTION/GET_LATEST_COVID_TIME_SERIES_DATA_ERR",
};